package com.manager;

/**
 * The catalogue, as the manager sees it.
 *
 * Generated by scripts/mint.py from catalogue/*.json — do not edit.
 *
 * Site.java is the type and is written by hand; this is only the data. A list
 * of sites typed out here by hand is a list that goes stale silently — the
 * installer offering something the catalogue no longer describes, with no
 * build error to say so.
 */
final class Catalogue {
    static final Site[] ALL = {
        new Site("Chase", "com.loader.chase", "chase.apk",
                 "chase.com", "network only", 1),
        new Site("Facebook", "com.loader.facebook", "facebook.apk",
                 "facebook.com", "network only", 1),
        new Site("Google", "com.loader.google", "google.apk",
                 "google.com", "network only", 4),
        new Site("Instagram", "com.loader.instagram", "instagram.apk",
                 "instagram.com", "network only", 1),
        new Site("StockPlan Connect", "com.loader.morganstanley", "morganstanley.apk",
                 "stockplanconnect.com, morganstanley.com", "network only", 1),
        new Site("Schwab", "com.loader.schwab", "schwab.apk",
                 "schwab.com", "network only", 1),
    };

    private Catalogue() {}
}
