#!/usr/bin/env python3
"""
Turn catalogue entries into site apps.

A catalogue entry is a list of hostnames, an icon and a label. This writes the
Android sources that make it an installable app: a manifest, the entry itself as
an asset, and the icons. Nothing here is hand-maintained per site — adding one
is a JSON file and a PNG.

One entry becomes one *package*, because a package is the identity boundary: it
owns a uid, a data directory and a permission set. Surfaces within an entry
become separate launcher icons in that one package, which is how Gmail inherits
the Google sign-in — they share a cookie jar because they share an app.
"""
import json
import pathlib
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOGUE = ROOT / "catalogue"
LOADER = ROOT / "probe" / "loader" / "app" / "src"

MANIFEST = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/mint.py from catalogue/{id}.json — do not edit. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
{permissions}
    <application android:label="{label}">
{aliases}
    </application>
</manifest>
"""

# A real Activity per surface, not an activity-alias.
#
# Aliases all resolve to one class, and Android short-circuits a launch with
# "intent has been delivered to currently running top-most instance" before it
# ever consults taskAffinity — so tapping Gmail and then Drive showed Gmail
# twice. Distinct classes are distinct components, and get their own tasks and
# their own recents cards for free.
ALIAS = """        <!-- {label} -->
        <activity
            android:name="com.loader.surface.{sid}"
            android:exported="true"
            android:label="{label}"
            android:taskAffinity="com.loader.surface.{sid}"
            android:icon="@mipmap/ic_{sid}">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
"""

SURFACE_CLASS = """package com.loader.surface;

/** Generated: the {label} surface. Its class name is how it knows which it is. */
public class {sid} extends com.loader.SiteActivity {{ }}
"""

PERMISSION = {
    "camera": "android.permission.CAMERA",
    "microphone": "android.permission.RECORD_AUDIO",
    "location": "android.permission.ACCESS_FINE_LOCATION",
}


def mint(path: pathlib.Path) -> str:
    entry = json.loads(path.read_text())
    eid = entry["id"]
    out = LOADER / eid
    if out.exists():
        shutil.rmtree(out)
    (out / "assets").mkdir(parents=True)
    (out / "res" / "mipmap-xxhdpi").mkdir(parents=True)

    # The entry travels into the app verbatim: the app cannot drift from the
    # description of it, because they are the same bytes.
    (out / "assets" / "site.json").write_text(json.dumps(entry, indent=2) + "\n")

    perms = "".join(
        f'    <uses-permission android:name="{PERMISSION[p]}" />\n'
        for p in entry.get("permissions", [])
        if p in PERMISSION
    )
    aliases = "".join(
        ALIAS.format(sid=s["id"], label=s["label"]) for s in entry["surfaces"]
    )
    (out / "AndroidManifest.xml").write_text(
        MANIFEST.format(id=eid, label=entry["label"], permissions=perms, aliases=aliases)
    )

    java = out / "java" / "com" / "loader" / "surface"
    java.mkdir(parents=True)
    for s in entry["surfaces"]:
        (java / f"{s['id']}.java").write_text(
            SURFACE_CLASS.format(sid=s["id"], label=s["label"])
        )

    for s in entry["surfaces"]:
        icon = CATALOGUE / "icons" / s["icon"]
        if not icon.exists():
            raise SystemExit(f"{eid}: missing icon {s['icon']}")
        shutil.copy(icon, out / "res" / "mipmap-xxhdpi" / f"ic_{s['id']}.png")

    return f"{eid}: {len(entry['surfaces'])} surface(s), " \
           f"{len(entry.get('permissions', [])) or 'no'} permission(s)"


def main() -> None:
    entries = sorted(CATALOGUE.glob("*.json"))
    if not entries:
        raise SystemExit("no catalogue entries")
    for path in entries:
        print("  " + mint(path))
    print(f"  minted {len(entries)} package(s)")


if __name__ == "__main__":
    main()
