#!/usr/bin/env python3
"""
Turn catalogue entries into site apps.

A catalogue entry is a list of hostnames, an icon and a label. This writes the
Android sources that make it an installable app: a manifest, the entry itself as
an asset, and the icons. Nothing here is hand-maintained per site — adding one
is a JSON file and a PNG.

One entry becomes one *package*, because a package is the identity boundary: it
owns a uid, a data directory and a permission set. Surfaces within an entry
become separate launcher icons in that one package, which is how Gmail inherits
the Google sign-in — they share a cookie jar because they share an app.

It also writes the manager's copy of the catalogue. The manager used to carry a
hand-written list, which drifted the moment the catalogue changed and left the
installer offering three sites that no longer existed. Anything naming a site
is generated from here or it will be wrong eventually.

    ./mint.py            regenerate everything from catalogue/*.json
    ./mint.py --check    verify the checked-in output is current, write nothing
"""
import json
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
CATALOGUE = ROOT / "catalogue"
LOADER = ROOT / "probe" / "loader" / "app" / "src"
MANAGER = ROOT / "probe" / "manager" / "app" / "src" / "main"

BANNER = "Generated by scripts/mint.py from catalogue/*.json — do not edit."

MANIFEST = """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by scripts/mint.py from catalogue/{id}.json — do not edit. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
{permissions}
    <application android:label="{label}">
{aliases}
    </application>
</manifest>
"""

# A real Activity per surface, not an activity-alias.
#
# Aliases all resolve to one class, and Android short-circuits a launch with
# "intent has been delivered to currently running top-most instance" before it
# ever consults taskAffinity — so tapping Gmail and then Drive showed Gmail
# twice. Distinct classes are distinct components, and get their own tasks and
# their own recents cards for free.
ALIAS = """        <!-- {label} -->
        <activity
            android:name="com.loader.surface.{sid}"
            android:exported="true"
            android:label="{label}"
            android:taskAffinity="com.loader.surface.{sid}"
            android:icon="@mipmap/ic_{sid}">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
"""

SURFACE_CLASS = """package com.loader.surface;

/** Generated: the {label} surface. Its class name is how it knows which it is. */
public class {sid} extends com.loader.SiteActivity {{ }}
"""

CATALOGUE_CLASS = """package com.manager;

/**
 * The catalogue, as the manager sees it.
 *
 * {banner}
 *
 * Site.java is the type and is written by hand; this is only the data. A list
 * of sites typed out here by hand is a list that goes stale silently — the
 * installer offering something the catalogue no longer describes, with no
 * build error to say so.
 */
final class Catalogue {{
    static final Site[] ALL = {{
{rows}    }};

    private Catalogue() {{}}
}}
"""

CATALOGUE_ROW = """        new Site("{label}", "{pkg}", "{asset}",
                 "{url}", "{permissions}", {surfaces}),
"""

MANAGER_MANIFEST = """<?xml version="1.0" encoding="utf-8"?>
<!-- {banner} -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <uses-permission android:name="android.permission.INTERNET" />
    <!-- Installing a site app is a package install, confirmed by the user each
         time. That friction is correct: it is the moment something gains an
         identity and a permission set of its own. -->
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />

    <!-- Android 11+ hides other packages. We need to see the engine and the
         site apps to report what is installed. Package visibility cannot be
         wildcarded, so every site is named — which is exactly why this file is
         generated rather than maintained. -->
    <queries>
        <package android:name="com.pane" />
{packages}    </queries>

    <application android:label="Sites" android:theme="@android:style/Theme.DeviceDefault">
        <activity android:name=".CatalogueActivity" android:exported="true">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <receiver android:name=".InstallResult" android:exported="false" />
    </application>
</manifest>
"""

PERMISSION = {
    "camera": "android.permission.CAMERA",
    "microphone": "android.permission.RECORD_AUDIO",
    "location": "android.permission.ACCESS_FINE_LOCATION",
}

# What the manager shows under a site's name. Every site app gets the network;
# saying so makes the empty case read as a fact rather than as missing data.
PERMISSION_LABEL = {"camera": "camera", "microphone": "microphone", "location": "location"}

# An id becomes a package suffix *and* a Java class name, so it has to be legal
# as both. Anything outside this produces a build failure a long way from here.
ID = re.compile(r"[a-z][a-z0-9]*\Z")

# An origin is a bare hostname. Not a URL, not a pattern: matching is
# host-or-suffix, so `chase.com` already covers every subdomain, and a regular
# expression here would be an open redirect waiting for a reviewer to miss it.
HOST = re.compile(r"[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+\Z")

JAVA_KEYWORDS = {
    "abstract", "assert", "boolean", "break", "byte", "case", "catch", "char",
    "class", "const", "continue", "default", "do", "double", "else", "enum",
    "extends", "final", "finally", "float", "for", "goto", "if", "implements",
    "import", "instanceof", "int", "interface", "long", "native", "new",
    "package", "private", "protected", "public", "return", "short", "static",
    "strictfp", "super", "switch", "synchronized", "this", "throw", "throws",
    "transient", "try", "void", "volatile", "while", "record", "var", "yield",
}


class CatalogueError(Exception):
    """One entry, every problem with it. Reporting them one at a time makes a
    contributor pay a round trip per typo."""

    def __init__(self, name: str, problems: list[str]):
        super().__init__(f"{name}: " + "; ".join(problems))
        self.name = name
        self.problems = problems


def covers(origins: list[str], host: str) -> bool:
    """The fence rule, in Python: host-or-suffix. Mirrors Origins.allowed."""
    return any(host == o or host.endswith("." + o) for o in origins)


def load(path: pathlib.Path) -> dict:
    """Reads an entry and refuses it unless it is one.

    Every check here is something that otherwise fails far from its cause: at
    Gradle configuration time, at manifest merge, or — worst — on the device, as
    an app that ejects itself the moment it opens.
    """
    bad: list[str] = []
    try:
        entry = json.loads(path.read_text())
    except json.JSONDecodeError as e:
        raise CatalogueError(path.name, [f"not valid JSON: {e}"]) from e
    if not isinstance(entry, dict):
        raise CatalogueError(path.name, ["not a JSON object"])

    eid = entry.get("id")
    if not isinstance(eid, str) or not ID.match(eid):
        bad.append(f"id {eid!r} must match {ID.pattern}")
    elif eid != path.stem:
        # The filename is what makes ids unique without a registry, and what
        # the flavour is named after.
        bad.append(f"id {eid!r} does not match filename {path.stem!r}")
    if not isinstance(entry.get("label"), str) or not entry["label"].strip():
        bad.append("label must be a non-empty string")

    for p in entry.get("permissions", []):
        if p not in PERMISSION:
            bad.append(f"unknown permission {p!r}, expected one of {sorted(PERMISSION)}")
    if entry.get("permissions") and not str(entry.get("note", "")).strip():
        # Not a rule against permissions — a rule that one is never silent.
        # Adding `camera` to a bank is a security change, and the point of
        # requiring prose is that the diff cannot be small.
        bad.append("declares permissions and must carry a note saying why")

    surfaces = entry.get("surfaces")
    if not isinstance(surfaces, list) or not surfaces:
        raise CatalogueError(path.name, bad + ["surfaces must be a non-empty list"])

    seen: set[str] = set()
    for s in surfaces:
        sid = s.get("id")
        where = f"surface {sid!r}"
        if not isinstance(sid, str) or not ID.match(sid):
            bad.append(f"{where}: id must match {ID.pattern}")
            continue
        if sid in JAVA_KEYWORDS:
            bad.append(f"{where}: id is a Java keyword and becomes a class name")
        if sid in seen:
            # Two surfaces with one id would collide on the generated class,
            # the icon and the taskAffinity all at once.
            bad.append(f"{where}: duplicate surface id")
        seen.add(sid)

        if not isinstance(s.get("label"), str) or not s["label"].strip():
            bad.append(f"{where}: label must be a non-empty string")

        origins = s.get("origins")
        if not isinstance(origins, list) or not origins:
            bad.append(f"{where}: origins must be a non-empty list")
            origins = []
        for o in origins:
            if not isinstance(o, str) or not HOST.match(o):
                bad.append(f"{where}: origin {o!r} must be a bare lowercase hostname")

        home = s.get("home")
        if not isinstance(home, str) or not home.startswith("https://"):
            bad.append(f"{where}: home must be an https:// URL")
        elif origins and all(isinstance(o, str) for o in origins):
            # An app whose home is outside its own fence ejects on launch, and
            # the report is "it opens to a dialog", which is a long way from
            # "the allowlist is missing a host".
            host = home[len("https://"):].split("/")[0].split(":")[0].lower()
            if not covers(origins, host):
                bad.append(f"{where}: home host {host!r} is outside its own origins {origins}")

        icon = s.get("icon")
        if not isinstance(icon, str) or not icon:
            bad.append(f"{where}: icon must be a filename in catalogue/icons/")
        elif not (CATALOGUE / "icons" / icon).exists():
            bad.append(f"{where}: missing icon {icon}")

    if bad:
        raise CatalogueError(path.name, bad)
    return entry


def mint_loader(entry: dict, out: pathlib.Path) -> None:
    """One catalogue entry becomes one flavour source set."""
    eid = entry["id"]
    (out / "assets").mkdir(parents=True)
    (out / "res" / "mipmap-xxhdpi").mkdir(parents=True)

    # The entry travels into the app verbatim: the app cannot drift from the
    # description of it, because they are the same bytes.
    (out / "assets" / "site.json").write_text(json.dumps(entry, indent=2) + "\n")

    perms = "".join(
        f'    <uses-permission android:name="{PERMISSION[p]}" />\n'
        for p in entry.get("permissions", [])
    )
    aliases = "".join(
        ALIAS.format(sid=s["id"], label=s["label"]) for s in entry["surfaces"]
    )
    (out / "AndroidManifest.xml").write_text(
        MANIFEST.format(id=eid, label=entry["label"], permissions=perms, aliases=aliases)
    )

    java = out / "java" / "com" / "loader" / "surface"
    java.mkdir(parents=True)
    for s in entry["surfaces"]:
        (java / f"{s['id']}.java").write_text(
            SURFACE_CLASS.format(sid=s["id"], label=s["label"])
        )
        shutil.copy(
            CATALOGUE / "icons" / s["icon"],
            out / "res" / "mipmap-xxhdpi" / f"ic_{s['id']}.png",
        )


def permission_label(entry: dict) -> str:
    """What the manager prints, and the honest part of that screen: it is the
    ceiling on what the site can ever reach, not a preference."""
    extra = [PERMISSION_LABEL[p] for p in entry.get("permissions", [])]
    return "network only" if not extra else "network, " + ", ".join(extra)


def manager_files(entries: list[dict]) -> dict[pathlib.Path, str]:
    """The manager's view of the catalogue: what to list, and what to install."""
    rows = ""
    packages = ""
    for e in entries:
        # Every origin the entry can reach, deduped in first-seen order. The
        # manager is claiming where an app may go, so it says all of it.
        origins: list[str] = []
        for s in e["surfaces"]:
            for o in s["origins"]:
                if o not in origins:
                    origins.append(o)
        rows += CATALOGUE_ROW.format(
            label=e["label"],
            pkg=f"com.loader.{e['id']}",
            asset=f"{e['id']}.apk",
            url=", ".join(origins),
            permissions=permission_label(e),
            surfaces=len(e["surfaces"]),
        )
        packages += f'        <package android:name="com.loader.{e["id"]}" />\n'

    return {
        MANAGER / "java" / "com" / "manager" / "Catalogue.java":
            CATALOGUE_CLASS.format(banner=BANNER, rows=rows),
        MANAGER / "AndroidManifest.xml":
            MANAGER_MANIFEST.format(banner=BANNER, packages=packages),
    }


def entries() -> list[pathlib.Path]:
    return sorted(CATALOGUE.glob("*.json"))


def main() -> None:
    check = "--check" in sys.argv[1:]
    paths = entries()
    if not paths:
        raise SystemExit("no catalogue entries")

    loaded = []
    problems = []
    for path in paths:
        try:
            loaded.append(load(path))
        except CatalogueError as e:
            problems.append(str(e))
    if problems:
        raise SystemExit("\n".join("  " + p for p in problems))

    stale: list[str] = []
    for entry, path in zip(loaded, paths):
        out = LOADER / entry["id"]
        if check:
            stale += compare_tree(entry, out)
        else:
            if out.exists():
                shutil.rmtree(out)
            mint_loader(entry, out)
            print(f"  {entry['id']}: {len(entry['surfaces'])} surface(s), "
                  f"{len(entry.get('permissions', [])) or 'no'} permission(s)")

    for target, text in manager_files(loaded).items():
        if check:
            if not target.exists() or target.read_text() != text:
                stale.append(str(target.relative_to(ROOT)))
        else:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(text)

    if check:
        if stale:
            raise SystemExit(
                "generated output is stale — run scripts/mint.py:\n"
                + "\n".join("  " + s for s in sorted(set(stale)))
            )
        print(f"  {len(loaded)} entries, generated output is current")
    else:
        print(f"  minted {len(loaded)} package(s), and the manager's catalogue")


def compare_tree(entry: dict, out: pathlib.Path) -> list[str]:
    """Mints into a scratch directory and diffs, so --check needs no knowledge
    of the layout beyond what mint_loader already has."""
    import tempfile

    stale = []
    with tempfile.TemporaryDirectory() as tmp:
        want = pathlib.Path(tmp) / entry["id"]
        mint_loader(entry, want)
        wanted = {p.relative_to(want) for p in want.rglob("*") if p.is_file()}
        have = {p.relative_to(out) for p in out.rglob("*") if p.is_file()} if out.exists() else set()
        for rel in sorted(wanted | have):
            a, b = want / rel, out / rel
            if not b.exists() or not a.exists() or a.read_bytes() != b.read_bytes():
                stale.append(str((out / rel).relative_to(ROOT)))
    return stale


if __name__ == "__main__":
    main()
